### ISSUE TITLE
getch '\n' on windows

### ISSUE THREAD

**Issue by Kalin-Rudnicki** [ruby/io-console#3] opened 2019-02-24 04:54 UTC
```ruby
require 'io/console'

loop do
    puts($stdin.getch.inspect)
end

# KeyPresses:
# A => "A"
# B => "B"
# \n => nothing...
# C => "\n"
# D => returns twice "C" "D"
```

**Comment by nobu** [comment] 2019-11-20 06:46
I cannot reproduce it.
What key do you press for `\n`?

**Comment by orgads** [comment] 2019-12-01 15:13
Here too, on Win10. See also https://github.com/JEG2/highline/issues/244

I press Enter.

**Comment by orgads** [comment] 2019-12-01 15:33
```
ruby -v
ruby 2.5.6p201 (2019-08-28 revision 67796) [x64-mingw32]
```

**Comment by orgads** [comment] 2019-12-02 08:43
Same on Win7.

**Comment by nobu** [comment] 2019-12-02 23:28
The io-console bundled with 2.5 is quite old.
Could you try more recent versions?

**Comment by orgads** [comment] 2019-12-03 06:57
With the latest gem release it's the same, but with master here it kinda works. I get \r when pressing Enter (why not \n?)

Not sure if this is intended, but if I press Ctrl-C with the existing version I get char 3, but with master I get an Interrupt exception.

**Comment by orgads** [comment] 2019-12-03 07:15
I bisected the issue, and it was fixed in fae7933c4a74e225df2e09fdedea0efe9b8c7968, which is included in 0.5.0.

Can you please push 0.5.0 to rubygems.org?

**Comment by orgads** [comment] 2019-12-03 07:18
On linux (debian) Enter produces \r as well, but Ctrl-C gives \u0003 and does not raise an exception.

**Comment by nobu** [comment] 2019-12-04 01:32
Fixed Ctrl-C issue on Windows now, thank you for the pointing out.
`\r`(= Ctrl-M) is the expected code for Enter.
It is translated to `\n` by console drivers when it is in "cooked" mode, and `getch` bypasses it.

**Comment by orgads** [comment] 2019-12-09 06:48
You may close this issue.

Can you please also publish binary packages for mingw to rubygems?

**Comment by nobu** [comment] 2019-12-10 00:43
We have dropped the binary gem support at 972ceb081d67cf14fec0471f70305f68dbf32c97.
c.f. https://github.com/ruby/bigdecimal/pull/148

**Closed by nobu** 2019-12-10 00:43 UTC
